require: rubocop-rails

AllCops:
  Exclude:
    - '/vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: true

Layout/LineLength:
  Max: 122

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 500

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 250

Style/Documentation:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false